This PR creates the first stable release of the EasyPay app
limavfabio/easy_pay pull request #1
Opened 2023-06-09 17:20 UTC by limavfabio

Notable changes and features includes:
- A groups page where a user can create groups to separate and organize their payments
- A payments where a user can see all of his payments
- A user can see only the payments for a specific group ordered by most recent
- Login and Signup pages for user registration using devise
- Tests for models and requests

2023-06-09 22:33 UTC, Lucas-Masaba requested changes
# Hello @limavfabio  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 
- Written tests passing :heavy_check_mark: 
- Good job following Gitflow :potable_water: 
- Well written pull request description :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 22:33 UTC, Lucas-Masaba commented on README.md
> +  <img src="./app/assets/images/form.png" alt="form" width="45%"  height="100%" />
- [x] These images can not be seen on the README. Please make sure these images are displayed so that your README can look professional

2023-06-09 22:33 UTC, Lucas-Masaba commented on README.md
> +
- [ ] Please add the `Future Features` header as seen in the default README and describe the new features you will add to this project.

2023-06-09 22:33 UTC, Lucas-Masaba commented on README.md
> +This project is [MIT](./license) licensed
- [ ] This link leads to a 404 page. Please fix this.
![image](https://github.com/limavfabio/easy_pay/assets/45460192/cc38ddb8-92d8-40bd-96cb-f7df121fa5b9)

2023-06-09 22:33 UTC, Lucas-Masaba commented on README.md
> +- A short video presentation of the app can be found here: https://www.loom.com/share/deedde777ef24f7fb5dbe4c1be928a6e
- [ ] You explained the features of your project well. However, you did not highlight a piece of the code you find interesting or proud of making. Please add that since it is a project requirement :+1:

2023-06-09 22:33 UTC, Lucas-Masaba commented on README.md
> +- A live version of this app can be found at: https://easy-pay-dcix.onrender.com/
- [ ] I am having a hard time with your deployed project here. Whenever I try to sign up, I get this error
![image](https://github.com/limavfabio/easy_pay/assets/45460192/bff2e1ff-a632-4d99-bb41-927525774a37)
When I try signing in again, it says user already exists. When I try to log in with the user I created, I get the same error message
![image](https://github.com/limavfabio/easy_pay/assets/45460192/79c3106d-2ae2-436c-ac1f-9fccf6bce08b)
I can't seem to go anywhere else on the page. If you are experiencing the same issues with your deployment, could you please fix it

2023-06-09 22:33 UTC, Lucas-Masaba commented on app/views/groups/show.html.erb
> +<div class='flex justify-center'><%= link_to "New payment for this group",
- [ ] Please make sure this button looks similar to that as seen in the original design.
### Your Implementation
![image](https://github.com/limavfabio/easy_pay/assets/45460192/6611747f-a9f8-4396-923e-85c8dce3a9f6)
### Required
![image](https://github.com/limavfabio/easy_pay/assets/45460192/9ec09446-5092-4105-b9fc-c879fbf762e0)

2023-06-09 22:33 UTC, Lucas-Masaba commented on app/views/groups/index.html.erb
> +  <div class='border p-3 border-white text-center sticky'><%= link_to "New Group", new_group_path, class: "text-white" %></div>
- [ ] Well done on implementing this button, However, according to the instructions, after creating a group, the user should be redirected to the home page. But when I create the group, I'm not redirected to the home page. Instead, I'm redirected to the groups  show page:
![image](https://github.com/limavfabio/easy_pay/assets/45460192/872ead01-172e-41c8-9c24-1a898a03f9a5)

2023-06-09 22:33 UTC, Lucas-Masaba commented on app/views/payments/_form.html.erb
> +
- [ ] According to the project requirements, when I create a payment, I should be redirected to the payments page but instead, I am redirected to this page 
![image](https://github.com/limavfabio/easy_pay/assets/45460192/c662be5c-2ec5-4610-9f53-fb6dfcb64a61)

2023-06-10 14:06 UTC, Qoosim reviewed
#  *Status: Invalid Request* :red_circle: 

Hi @limavfabio, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif)

## Invalid Code Review Request

You have submitted a project, that has linter error. Kindly fix that
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-10 14:37 UTC, ichala requested changes
Hi Student
Good job so far! 
👏👏👏 
You still need to work on some issues to go to the next project, but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Updated Redirections  ✔️ 
- Updated Readme ✔️ 


 ## Required Changes ♻️

- [ ] **_🛑 as mentioned by the previous reviewer : ' You explained the features of your project well. However, you did not highlight a piece of the code you find interesting or proud of making. Please add that since it is a project requirement '_**






## Optional suggestions

- **Good job on fixing the deployment link by changing to render , and i know that the failing message in your repo is not a linter error, i highly recommend that you remove that test from the PR since you are not using railways anymore**

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 20:43 UTC, alexander16108 requested changes
Hi @limavfabio , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/11c7UUfN4eoHF6/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

- as suggested previously you should highlight a piece of `code` you find interesting. meaning you should show from your code base or virtual studio a piece of code u find interesting not from your live version 👍🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 21:01 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @limavfabio,

To highlight 👍🏽 
✔️ App runs smoothly
✔️ Video meets requirements

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/749155b89333c6d89386f5c98dd110e234a00f2aa1e864a5b3fecaf089aedb27/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f36664a31424d375232454252446e784b2f67697068792e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 21:01 UTC, merged